# Generated by Django 4.2.1 on 2023-05-29 13:28

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Korisnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('slika', models.ImageField(null=True, upload_to='imgs/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'db_table': 'korisnik',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Kviz',
            fields=[
                ('idkviz', models.AutoField(db_column='idKviz', primary_key=True, serialize=False)),
                ('naslov', models.CharField(max_length=255)),
                ('opis', models.TextField()),
                ('datumvreme', models.DateTimeField(db_column='datumVreme')),
                ('adresa', models.CharField(max_length=255)),
                ('kotizacija', models.IntegerField()),
                ('kapacitet', models.IntegerField()),
                ('zauzetost', models.IntegerField()),
                ('slika', models.ImageField(null=True, upload_to='imgs/')),
            ],
            options={
                'db_table': 'kviz',
            },
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('idtem', models.AutoField(db_column='idTem', primary_key=True, serialize=False)),
                ('naziv', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tema',
            },
        ),
        migrations.CreateModel(
            name='Uloga',
            fields=[
                ('idulo', models.AutoField(db_column='idUlo', primary_key=True, serialize=False)),
                ('naziv', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'uloga',
            },
        ),
        migrations.CreateModel(
            name='Organizator',
            fields=[
                ('opis', models.TextField()),
                ('brkvizova', models.IntegerField(db_column='brKvizova')),
                ('naziv', models.CharField(max_length=255)),
                ('idorg', models.OneToOneField(db_column='idOrg', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('odobren', models.IntegerField()),
                ('slika', models.ImageField(null=True, upload_to='imgs/')),
            ],
            options={
                'db_table': 'organizator',
            },
        ),
        migrations.CreateModel(
            name='Prijava',
            fields=[
                ('idpri', models.AutoField(db_column='idPri', primary_key=True, serialize=False)),
                ('nazivtima', models.CharField(db_column='nazivTima', max_length=45)),
                ('brclanova', models.IntegerField(db_column='brClanova')),
                ('idkor', models.ForeignKey(db_column='idKor', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('idkviz', models.ForeignKey(db_column='idKviz', on_delete=django.db.models.deletion.DO_NOTHING, to='zzp.kviz')),
            ],
            options={
                'db_table': 'prijava',
            },
        ),
        migrations.AddField(
            model_name='kviz',
            name='idtem',
            field=models.ForeignKey(db_column='idTem', on_delete=django.db.models.deletion.DO_NOTHING, to='zzp.tema'),
        ),
        migrations.AddField(
            model_name='korisnik',
            name='idulo',
            field=models.ForeignKey(db_column='idUlo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='zzp.uloga'),
        ),
        migrations.AddField(
            model_name='korisnik',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='Recenzija',
            fields=[
                ('idrec', models.AutoField(db_column='idRec', primary_key=True, serialize=False)),
                ('ocena', models.IntegerField()),
                ('komentar', models.TextField()),
                ('datumvreme', models.DateTimeField(db_column='datumVreme')),
                ('idkorrec', models.ForeignKey(db_column='idKorRec', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('idorgrec', models.ForeignKey(db_column='idOrgRec', on_delete=django.db.models.deletion.DO_NOTHING, to='zzp.organizator')),
            ],
            options={
                'db_table': 'recenzija',
            },
        ),
        migrations.AddField(
            model_name='kviz',
            name='idorg',
            field=models.ForeignKey(db_column='idOrg', on_delete=django.db.models.deletion.DO_NOTHING, to='zzp.organizator'),
        ),
    ]
