# Generated by Django 4.2.1 on 2023-06-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zzp', '0002_organizator_teme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='korisnik',
            name='slika',
            field=models.ImageField(blank=True, null=True, upload_to='imgs/'),
        ),
    ]
