# Generated by Django 4.2.1 on 2023-06-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zzp', '0003_alter_korisnik_slika'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kviz',
            name='zauzetost',
            field=models.IntegerField(default=0),
        ),
    ]
