# Generated by Django 4.2.1 on 2023-06-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zzp', '0004_alter_kviz_zauzetost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizator',
            name='brkvizova',
            field=models.IntegerField(db_column='brKvizova', default=0),
        ),
    ]
