# Generated by Django 4.2.1 on 2023-06-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zzp', '0005_alter_organizator_brkvizova'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizator',
            name='odobren',
            field=models.IntegerField(default=0),
        ),
    ]
