# Generated by Django 4.2.1 on 2023-06-05 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zzp', '0006_alter_organizator_odobren'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizator',
            name='predstojecikviz',
            field=models.ForeignKey(db_column='predstojeciKviz', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='zzp.kviz'),
        ),
    ]
