# Generated by Django 4.2.1 on 2023-06-06 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zzp', '0007_organizator_predstojecikviz'),
    ]

    operations = [
        migrations.AddField(
            model_name='korisnik',
            name='odobren',
            field=models.IntegerField(default=0),
        ),
    ]
