# Generated by Django 4.2.1 on 2023-06-06 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zzp', '0008_korisnik_odobren'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='korisnik',
            name='slika',
        ),
    ]
