# Generated by Django 4.2.1 on 2023-06-06 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zzp', '0010_alter_kviz_idorg_alter_organizator_predstojecikviz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizator',
            name='idorg',
            field=models.OneToOneField(db_column='idOrg', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
